name: Build PCFX Tools Windows
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build All Tools
        run: |
          make
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: pcfx-tools-windows
          path: |
            pcfx-cdlink/pcfx-cdlink.exe
            pcfx-711/pcfx-711.exe
